### ISSUE TITLE
Blog Atom and RSS feeds

### ISSUE THREAD

**Issue by ThinkChaos** [xi-editor/xi-editor.github.io#1]
It would be nice to have a way to subscribe to news regarding Xi.

**Comment by cmyr** [comment]
Agreed!

**Comment by ryanbloom** [comment]
I installed the jekyll-feed plugin, which [seems to think Atom is better](https://github.com/jekyll/jekyll-feed#why-atom-and-not-rss). If we don't have a specific reason to support RSS, I'm inclined to just leave it at that?

(Most feed readers should recognize the meta tag, but the raw feed is at https://xi-editor.io/feed.xml)

**Comment by ThinkChaos** [comment]
The atom feed fits my personal needs, thanks!
